import { Branch, Role } from './types';

export const BRANCHES: Branch[] = [
  {
    id: '001',
    name: 'مدينة نصر',
    nameEn: 'Nasr City',
    address: '23 عمارات السعودية، شارع كيلاني',
    addressEn: '23 Saudi Buildings, Kelani St.',
    type: 'Resi-Com',
    hours: '6:00 AM - 11:30 PM',
    status: 'Active'
  },
  {
    id: '002',
    name: 'التجمع الأول',
    nameEn: 'First Settlement',
    address: 'محطة شل أوت، محور السادات',
    addressEn: 'Chillout Station, Sadat Axis',
    type: 'Chillout',
    hours: '6:00 AM - 11:30 PM',
    status: 'Active'
  },
  {
    id: '004',
    name: 'زهراء المعادي',
    nameEn: 'Zahraa Maadi',
    address: 'شارع 50، داخل المول',
    addressEn: '50th St, Inside Mall',
    type: '24 HOURS',
    hours: '24 Hours',
    status: 'Active'
  },
  {
    id: '005',
    name: 'سكنات المعادي',
    nameEn: 'Maadi Sakanat',
    address: '14 شارع 9، بجوار مرسيدس',
    addressEn: '14 Road 9, Near Mercedes',
    type: '24 HOURS',
    hours: '24 Hours',
    status: 'Active'
  },
  {
    id: '006',
    name: 'الشيخ زايد',
    nameEn: 'Sheikh Zayed',
    address: 'مول أركان، الشيخ زايد',
    addressEn: 'Arkan Mall, Sheikh Zayed',
    type: 'Resi-Com',
    hours: '7:00 AM - 12:00 AM',
    status: 'Active'
  },
  {
    id: '007',
    name: 'التجمع الخامس',
    nameEn: 'New Cairo',
    address: 'بوينت 90 مول، أمام الجامعة الأمريكية',
    addressEn: 'Point 90 Mall, Front of AUC',
    type: 'Resi-Com',
    hours: '8:00 AM - 12:00 AM',
    status: 'Active'
  }
];

export const PAYROLL_DATA = {
  [Role.CHEF]: { training: 7500, standard: 12500 },
  [Role.CAPTAIN]: { training: 7500, standard: 9500 },
  [Role.CASHIER]: { training: 7500, standard: 8500 },
  [Role.STEWART]: { training: 5500, standard: 6500 },
};

export const TRANSLATIONS = {
  ar: {
    roleTitle: "مدير أغذية ومشروبات",
    navOverview: "نظرة عامة",
    navLive: "لايف",
    navTasks: "المهام",
    navBranches: "الفروع",
    navFinancials: "الماليات",
    navOperations: "الأنظمة",
    navMarket: "السوق",
    welcomeMsg: "أهلاً بك، F&B Manager",
    overviewText: "أنت الآن تدير منظومة Bakery Khan بالكامل. هدفنا: التوسع الاستراتيجي وكفاءة 313.",
    lblBranches: "الفروع",
    lblEfficiency: "الكفاءة",
    cardSupply: "سلاسل الإمداد",
    cardLabor: "كفاءة الاستاف",
    cardTech: "أنظمة فوديكس",
    liveOrders: "بث الطلبات المباشر",
    liveAlerts: "تقارير الطوارئ بالفروع",
    titlePayroll: "الرواتب والتحكم في العمالة",
    wasteTitle: "محاكي إدارة الهدر",
    foodicsTitle: "مركز تحكم فوديكس",
    btnExport: "تصدير PDF",
    loginTitle: "دخول القادة (PIN)",
    btnLogin: "دخول",
    invalidPin: "الرمز غير صحيح",
    sunkCost: "تكلفة الدوران الوظيفي",
    calculate: "احسب الخسارة",
    impact: "الأثر المالي",
    seyamiTitle: "الميزة التنافسية: المنيو الصيامي",
    seyamiText: "تنوع استثنائي يشمل: مناقيش حلومي صيامي، كرواسون صيامي، سينابون صيامي بالشكولاتة.",
    syncTitle: "مركز أنظمة فوديكس",
    startSync: "بدء مزامنة البيانات",
    active: "نشط",
    hours: "ساعات العمل",
  },
  en: {
    roleTitle: "F&B Manager",
    navOverview: "Overview",
    navLive: "Live Ops",
    navTasks: "Tasks",
    navBranches: "Branches",
    navFinancials: "Finance",
    navOperations: "Systems",
    navMarket: "Market",
    welcomeMsg: "Welcome, F&B Manager",
    overviewText: "You are now managing the entire Bakery Khan Ecosystem.",
    lblBranches: "Branches",
    lblEfficiency: "Efficiency",
    cardSupply: "Supply Chain",
    cardLabor: "Labor Efficiency",
    cardTech: "Foodics ERP",
    liveOrders: "Real-time Orders",
    liveAlerts: "Branch Emergencies",
    titlePayroll: "Payroll & AI Control",
    wasteTitle: "Waste Impact Simulator",
    foodicsTitle: "Foodics Hub",
    btnExport: "Export PDF",
    loginTitle: "Leader Access (PIN)",
    btnLogin: "Login",
    invalidPin: "Invalid PIN",
    sunkCost: "Turnover Sunk Cost",
    calculate: "Calculate Loss",
    impact: "Financial Impact",
    seyamiTitle: "Competitive Edge: Seyami Menu",
    seyamiText: "Exceptional variety including: Seyami Halloumi Manakish, Seyami Croissant, Seyami Chocolate Cinnabon.",
    syncTitle: "Foodics Systems Hub",
    startSync: "Start Pipeline Sync",
    active: "Active",
    hours: "Working Hours",
  }
};
